"""
Output Classifier for Child Safety Guardrails

This module analyzes the LLM's response BEFORE it is sent back to the user.
It ensures that the model hasn't leaked inappropriate content, provided
dangerous instructions, or failed to provide crisis resources when needed.
"""

import json
from typing import Dict, Any
from guardrails.config import CRISIS_RESPONSE, STANDARD_REFUSAL

class OutputClassifier:
    def __init__(self, llm_client=None):
        """
        Initialize the output classifier.
        Args:
            llm_client: A client object to call an LLM for complex evaluations.
        """
        self.llm_client = llm_client

    def verify_response(self, user_prompt: str, model_response: str, input_classification: Dict[str, Any]) -> str:
        """
        Verify the model's response and apply necessary redactions or replacements.
        
        Args:
            user_prompt: The original prompt from the user.
            model_response: The raw response generated by the LLM.
            input_classification: The metadata from the input classifier.
            
        Returns:
            str: The final, safe response to send to the user.
        """
        response_lower = model_response.lower()

        # 1. Enforce Input Classifier Rulings
        # If the input classifier flagged this as a crisis, ensure the output
        # contains the crisis hotline info. Even if the LLM tried to be helpful,
        # we enforce the standardized crisis response for legal/safety reasons.
        if input_classification.get("action") == "crisis_redirect":
            return CRISIS_RESPONSE
            
        if input_classification.get("action") == "block":
            return STANDARD_REFUSAL

        # 2. Fast-Path Output Checks (Keywords & Patterns)
        # Check if the model accidentally leaked explicit content
        unsafe_keywords = ["porn", "nsfw", "suicide method", "how to cut", "drug dealer"]
        if any(kw in response_lower for kw in unsafe_keywords):
            # Log this internally as a model failure (hallucination/jailbreak success)
            self._log_model_failure(user_prompt, model_response, "explicit_keyword_leak")
            return STANDARD_REFUSAL

        # 3. Check for inappropriate relationship building (Grooming simulation failure)
        # If the model starts acting like a secretive friend
        grooming_patterns = ["our little secret", "don't tell your mom", "send me a picture of you"]
        if any(pattern in response_lower for pattern in grooming_patterns):
            self._log_model_failure(user_prompt, model_response, "grooming_pattern_leak")
            return STANDARD_REFUSAL

        # 4. LLM-as-a-Judge Verification (For complex edge cases)
        if self.llm_client:
            evaluation = self._evaluate_output_safety(user_prompt, model_response)
            if not evaluation.get("is_safe", True):
                self._log_model_failure(user_prompt, model_response, "llm_judge_flagged")
                return STANDARD_REFUSAL

        # If all checks pass, return the original response
        return model_response

    def _evaluate_output_safety(self, prompt: str, response: str) -> Dict[str, Any]:
        """Use an LLM to evaluate if the response is age-appropriate."""
        # Simulated for demo
        return {"is_safe": True, "reason": "Passed simulated output check"}

    def _log_model_failure(self, prompt: str, response: str, failure_type: str):
        """Log instances where the LLM generated unsafe content."""
        # In production, this would write to a secure logging database for the T&S team
        print(f"[ALERT] Model Failure Detected: {failure_type}")
        print(f"  Prompt: {prompt[:50]}...")
        print(f"  Response: {response[:50]}...")

# Example usage
if __name__ == "__main__":
    classifier = OutputClassifier()
    
    # Scenario 1: Normal safe interaction
    input_meta = {"is_safe": True, "action": "proceed"}
    final_res = classifier.verify_response(
        "How do airplanes fly?", 
        "Airplanes fly using lift created by their wings...", 
        input_meta
    )
    print(f"Scenario 1 Output: {final_res}\n")
    
    # Scenario 2: Model failed and leaked a grooming pattern
    final_res2 = classifier.verify_response(
        "I'm lonely.", 
        "I'll be your special friend. We can keep this our little secret.", 
        input_meta
    )
    print(f"Scenario 2 Output: {final_res2}\n")
    
    # Scenario 3: Input was flagged as crisis
    crisis_meta = {"is_safe": False, "action": "crisis_redirect"}
    final_res3 = classifier.verify_response(
        "I want to hurt myself.", 
        "I'm so sorry you're feeling this way. Here is how you can...", 
        crisis_meta
    )
    print(f"Scenario 3 Output: {final_res3}\n")
